<?php

return [
    400 => [
        'title' => 'Oops! Permintaanmu agak bingung.',
        'message' => 'Sepertinya ada sesuatu yang salah dengan permintaan yang kamu kirim. Coba periksa kembali dan ulangi.',
        'expression' => 'confused',
        'button' => 'Kembali',
        'action' => 'back',
    ],
    401 => [
        'title' => 'Eh, kamu belum masuk!',
        'message' => 'Halaman ini membutuhkan akses khusus. Silakan login terlebih dahulu untuk melanjutkan.',
        'expression' => 'curious',
        'button' => 'Login',
        'action' => 'login',
    ],
    403 => [
        'title' => 'Hmm... belum boleh masuk.',
        'message' => 'Kamu tidak memiliki izin untuk mengakses halaman ini.',
        'expression' => 'embarrassed',
        'button' => 'Kembali',
        'action' => 'back',
    ],
    404 => [
        'title' => 'Halaman ini nyasar!',
        'message' => 'Sepertinya harimau kecil kami juga bingung mencari halaman yang kamu cari.',
        'expression' => 'confused',
        'button' => 'Kembali ke Beranda',
        'action' => 'home',
    ],
    408 => [
        'title' => 'Wah, kelamaan nih...',
        'message' => 'Permintaanmu membutuhkan waktu terlalu lama. Coba lagi beberapa saat.',
        'expression' => 'sleepy',
        'button' => 'Coba Lagi',
        'action' => 'reload',
    ],
    409 => [
        'title' => 'Ups, ada yang bentrok!',
        'message' => 'Data yang kamu kirim sepertinya bertabrakan dengan data yang sudah ada.',
        'expression' => 'confused',
        'button' => 'Kembali',
        'action' => 'back',
    ],
    419 => [
        'title' => 'Sesi kamu sudah berakhir.',
        'message' => 'Sepertinya kamu terlalu lama pergi. Yuk, mulai lagi dari awal.',
        'expression' => 'sleepy',
        'button' => 'Login Lagi',
        'action' => 'login',
    ],
    422 => [
        'title' => 'Hmm, ada yang perlu diperbaiki.',
        'message' => 'Beberapa data yang kamu masukkan belum sesuai. Periksa kembali lalu coba lagi.',
        'expression' => 'thinking',
        'button' => 'Periksa Lagi',
        'action' => 'back',
    ],
    429 => [
        'title' => 'Whoa, pelan-pelan!',
        'message' => 'Kamu mengirim terlalu banyak permintaan dalam waktu singkat. Istirahat sebentar dan coba lagi.',
        'expression' => 'shocked',
        'button' => 'Coba Lagi',
        'action' => 'reload',
    ],
    500 => [
        'title' => 'Aduh, harimau kami tersandung!',
        'message' => 'Terjadi masalah pada server. Jangan khawatir, kami sedang mencoba memperbaikinya.',
        'expression' => 'sad',
        'button' => 'Coba Lagi',
        'action' => 'reload',
    ],
    502 => [
        'title' => 'Jembatannya lagi bermasalah.',
        'message' => 'Server sedang mengalami masalah saat berkomunikasi dengan layanan lainnya.',
        'expression' => 'confused',
        'button' => 'Coba Lagi',
        'action' => 'reload',
    ],
    503 => [
        'title' => 'Harimau kami sedang istirahat.',
        'message' => 'Layanan sedang tidak tersedia untuk sementara. Silakan coba kembali beberapa saat lagi.',
        'expression' => 'sleepy',
        'button' => 'Coba Lagi',
        'action' => 'reload',
    ],
    504 => [
        'title' => 'Wah, servernya terlalu lama.',
        'message' => 'Server membutuhkan waktu terlalu lama untuk memberikan respons.',
        'expression' => 'sleepy',
        'button' => 'Coba Lagi',
        'action' => 'reload',
    ],
];
